version: 1.0.9.{build}

image:
  - Visual Studio 2019
  - Ubuntu1804
  - macOS

environment:
  matrix:
    - BUILD_TYPE: Debug
    - BUILD_TYPE: Release

platform:
  - x86
  - x64
  - ARM

install:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" (
        choco install python --version=3.8.8;
    ) else (
        sudo apt-get -y install python3;
    )

before_build:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=%BUILD_TYPE%
  - cmake --build .

# test_script:
#   - ctest --output-on-failure