version: 1.0.9.{build}

platform:
  - x86
  - x64

configuration:
  - Release

image:
  - Visual Studio 2017
  - macOS
  - Ubuntu

before_build:
  - mkdir build
  - cd build
  - cmake -DADDMUSICK_COMPILE_AMKGUI=OFF ..

build_script:
  - cmake --build . 
