song_list:
  global:
    01: "originals/01 Miss.txt"
    02: "originals/02 Game Over.txt"
    03: "originals/03 Boss Clear.txt"
    04: "originals/04 Stage Clear.txt"
    05: "originals/05 Starman.txt"
    06: "originals/06 P-switch.txt"
    07: "originals/07 Keyhole.txt"
    08: "originals/08 Iris Out.txt"
    09: "originals/09 Bonus End.txt"

  local:
    0A: "originals/10 Piano.txt"
    0B: "originals/11 Here We Go.txt"
    0C: "originals/12 Water.txt"
    0D: "originals/13 Bowser.txt"
    0E: "originals/14 Boss.txt"
    0F: "originals/15 Cave.txt"
    10: "originals/16 Ghost.txt"
    11: "originals/17 Castle.txt"
    12: "originals/18 Switch Palace.txt"
    13: "originals/19 Welcome.txt"
    14: "originals/20 Rescue Egg.txt"
    15: "originals/21 Title.txt"
    16: "originals/22 Valley of Bowser Appears.txt"
    17: "originals/23 Overworld.txt"
    18: "originals/24 Yoshi's Island.txt"
    19: "originals/25 Vanilla Dome.txt"
    1A: "originals/26 Star Road.txt"
    1B: "originals/27 Forest of Illusion.txt"
    1C: "originals/28 Valley of Bowser.txt"
    1D: "originals/29 Special World.txt"
    1E: "originals/30 IntroScreen.txt"
    1F: "originals/31 Bowser Scene 2.txt"
    20: "originals/32 Bowser Scene 3.txt"
    21: "originals/33 Bowser Defeated.txt"
    22: "originals/34 Bowser Interlude.txt"
    23: "originals/35 Bowser Zoom In.txt"
    24: "originals/36 Bowser Zoom Out.txt"
    25: "originals/37 Princess Peach is Rescued.txt"
    26: "originals/38 Staff Roll.txt"
    27: "originals/39 The Yoshis Are Home.txt"
    28: "originals/40 Cast List.txt"

sample_groups:
  default:
    - "default/00 SMW @0.brr!"
    - "default/01 SMW @1.brr!"
    - "default/02 SMW @2.brr!"
    - "default/03 SMW @3.brr!"
    - "default/04 SMW @4.brr!"
    - "default/05 SMW @8.brr!"
    - "default/06 SMW @22.brr!"
    - "default/07 SMW @5.brr!"
    - "default/08 SMW @6.brr!"
    - "default/09 SMW @7.brr!"
    - "default/0A SMW @9.brr!"
    - "default/0B SMW @10.brr!"
    - "default/0C SMW @13.brr!"
    - "default/0D SMW @14.brr"
    - "default/0E SMW @29.brr!"
    - "default/0F SMW @21.brr"
    - "default/10 SMW @12.brr!"
    - "default/11 SMW @17.brr"
    - "default/12 SMW @15.brr!"
    - "default/13 SMW Thunder.brr!"

  optimized:
    - "optimized/00 SMW @0.brr!"
    - "optimized/01 SMW @1.brr!"
    - "optimized/02 SMW @2.brr!"
    - "optimized/03 SMW @3.brr!"
    - "optimized/04 SMW @4.brr!"
    - "optimized/05 SMW @8.brr!"
    - "optimized/06 SMW @22.brr!"
    - "optimized/07 SMW @5.brr!"
    - "optimized/08 SMW @6.brr!"
    - "optimized/09 SMW @7.brr!"
    - "optimized/0A SMW @9.brr!"
    - "optimized/0B SMW @10.brr!"
    - "optimized/0C SMW @13.brr!"
    - "optimized/0D SMW @14.brr"
    - "optimized/0E SMW @29.brr!"
    - "optimized/0F SMW @21.brr"
    - "optimized/10 SMW @12.brr!"
    - "optimized/11 SMW @17.brr"
    - "optimized/12 SMW @15.brr!"
    - "optimized/13 SMW Thunder.brr!"

  AMM:
    - "EMPTY.brr!"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"
    - "EMPTY.brr"

SFX:
  SFX1DF9:
    01:	"01 Hit head.txt"
    02:	"02 Contact.txt"
    03:	"03 Kick shell.txt"
    04:	"04 Pipe and hurt.txt"
    05:	"05 Midway point.txt"
    06:	"06 Yoshi gulp.txt"
    07:	"07 Dry bones collapse.txt"
    08:	"08 Spin jump kill.txt"
    09:	"09 Fly with cape.txt"
    0A:	"0A Get powerup.txt"
    0B:	"0B ON OFF switch.txt"
    0C:	"0C Item past goal.txt"
    0D:	"0D Get cape.txt"
    0E:	"0E Swim.txt"
    0F:	"0F Hurt while flying.txt"
    10:	"10 Magikoopa magic.txt"
    11:	"11 Pause.txt"
    12:	"12 Unpause.txt"
    13:	"13 Enemy stomp 1.txt"
    14:	"14 Enemy stomp 2.txt"
    15:	"15 Enemy stomp 3.txt"
    16:	"16 Enemy stomp 4.txt"
    17:	"17 Enemy stomp 5.txt"
    18:	"18 Enemy stomp 6.txt"
    19:	"19 Enemy stomp 7.txt"
    1A: "	1A Grinder click 1.txt"
    1B: "*	1A Grinder click 1.txt"
    1C:	"1C Yoshi coin.txt"
    1D:	"1D Time running low 1.txt"
    1E:	"1E P-balloon.txt"
    1F:	"1F Koopaling defeated.txt"
    20:	"20 Yoshi spit.txt"
    21: "?	21 Valley of Bowser appears.txt"
    22:	"22 Silence.txt"
    23:	"23 Lemmy and Wendy fall.txt"
    24: "*	22 Silence.txt"
    25:	"25 Blargg roar.txt"
    26:	"26 Firework whistle 1.txt"
    27:	"27 Firework bang 1.txt"
    28:	"28 Firework whistle 2.txt"
    29:	"29 Firework bang 2.txt"
    2A:	"2A Peach pops up.txt"
    2B:	"2B Jump.txt"
    2C:	"12 Unpause (silent).txt"
    2D:	"2D Grinder click 2.txt"
    2E:	"2B Jump (alt).txt"

  SFX1DFC:
    01:	"01 Coin.txt"
    02:	"02 Hit a prize block.txt"
    03:	"03 Hit a vine prize block.txt"
    04:	"04 Spin jump.txt"
    05:	"05 1-up.txt"
    06:	"06 Shoot fireball.txt"
    07:	"07 Shatter.txt"
    08:	"08 Springboard.txt"
    09:	"09 Bullet bill.txt"
    0A:	"0A Egg hatch.txt"
    0B:	"0B Item into reserve.txt"
    0C:	"0C Item from reserve.txt"
    0D:  "*	0C Item from reserve.txt"
    0E:	"0E L + R scroll.txt"
    0F:	"0F Door.txt"
    10: "*	09 Bullet bill.txt"
    11: "?	11 Drumroll.txt"
    12:	"12 Drumroll end.txt"
    13:	"13 Lose Yoshi.txt"
    14:	"14 Unused SMW2 SFX.txt"
    15:	"15 Overworld tile appears.txt"
    16:	"16 Overworld castle collapse.txt"
    17:	"17 Fire spit.txt"
    18:	"18 Thunder.txt"
    19:	"19 Clap + pop.txt"
    1A:	"1A Castle destruction bomb.txt"
    1B:	"1B Castle destruction fuse.txt"
    1C:	"1C Switch palace block ejection.txt"
    1D:	"1D Time low 2.txt"
    1E:	"1E Whistle.txt"
    1F:	"1F Yoshi.txt"
    20:	"20 Koopaling land in lava.txt"
    21:	"21 Yoshi tongue.txt"
    22:	"22 Message box.txt"
    23:	"23 Move onto overworld tile.txt"
    24:	"24 P-switch time low.txt"
    25:	"25 Yoshi enemy stomp.txt"
    26:	"26 Swooper.txt"
    27:	"27 Podoboo.txt"
    28:	"28 Enemy stunned.txt"
    29:	"29 Correct.txt"
    2A:	"2A Incorrect.txt"
    2B:	"2B Firework whistle.txt"
    2C:	"2C Firework bang.txt"
    2D:	"2D Podoboo -100% pan.txt"
    2E:	"2E Podoboo -71% pan.txt"
    2F:	"2F Podoboo -43% pan.txt"
    30:	"30 Podoboo -14% pan.txt"
    31:	"31 Podoboo 14% pan.txt"
    32:	"32 Podoboo 43% pan.txt"
    33:	"33 Podoboo 71% pan.txt"
    34:	"34 Podoboo 100% pan.txt"
    35:	"35 Jump.txt"
    36:	"36 Grinder click 2.txt"
    37:	"35 Jump (alt).txt"